server:
  port: 8080
spring:
  application:
    name: EcoVerse_be
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE:eco_verse_db}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#logging:
#  level:
#    root: warn
#    org.springframework.data.mongodb: INFO
#    org.springframework.security: INFO
#    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR