package com.sep490.ecoverse_be.enums;

public enum NotificationType {
    CAMPAIGN_INVITE,
    CAMPAIGN_START,
    CAMPAIGN_END,
    CAMPAIGN_CANCELLED,
    CAMPAIGN_JOINING,
    PARENT_APPROVAL_REQUEST,
    REWARD_AVAILABLE,
    REWARD_DELIVERED,
    PARTNERSHIP_REWARD_PREPARING,
    PARTNERSHIP_REWARD_SHIPPING,
    PARTNERSHIP_REWARD_ARRIVED,
    PARTNERSHIP_REWARD_DELIVERED,
    PARTNERSHIP_REWARD_CONFIRMED,
    LEADERBOARD_UPDATE,
    SYSTEM_ANNOUNCEMENT,
    SUBSCRIPTION_EXPIRING,
    SUBSCRIPTION_EXPIRED,
    COINS_EXPIRATION_WARNING,
    ROUND_ADVANCED,
    TITLE_EARNED
}
