package com.sep490.ecoverse_be.entity;

import com.sep490.ecoverse_be.enums.QuizCreated;
import com.sep490.ecoverse_be.enums.QuizDifficulty;
import com.sep490.ecoverse_be.enums.QuizSource;
import com.sep490.ecoverse_be.enums.QuizType;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

@Entity
@Table(name = "quizzes",
        indexes = {
                @Index(name = "idx_quizzes_school_id", columnList = "school_id"),
                @Index(name = "idx_quizzes_partnership_id", columnList = "partnership_id"),
                @Index(name = "idx_quizzes_difficulty", columnList = "difficulty"),
                @Index(name = "idx_quizzes_quiz_type", columnList = "quiz_type"),
                @Index(name = "idx_quizzes_source", columnList = "source"),
                @Index(name = "idx_quizzes_is_published", columnList = "is_published"),
                @Index(name = "idx_quizzes_target_grade", columnList = "target_grade")
        })
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class Quiz extends BaseEntity {

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "school_id")
    private School school;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "partnership_id")
    private Partnership partnership;

    @Column(nullable = false, length = 255)
    private String title;

    @Column(columnDefinition = "text")
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private QuizDifficulty difficulty;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private QuizType quizType;

    /**
     * MANUAL = created manually (direct input or CSV import).
     * AI_GENERATED = generated by AI; associated AiGenerationLog records the call.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private QuizSource source;

    // ── AI generation context ─────────────────────────────────────────────────

    /**
     * Grade level the quiz is tailored for (e.g. 3, 4, 5).
     * Provided by School/Partnership in the AI wizard; also useful for manual quizzes.
     * Used by AI to calibrate language complexity and question style.
     */
    @Column(name = "target_grade")
    private Integer targetGrade;

    /**
     * Number of questions in this quiz.
     * For AI-generated quizzes: set from the wizard input (min 10, max 20).
     * For manual quizzes: computed from question count at publish time.
     */
    @Column(name = "question_count")
    private Integer questionCount;

    /**
     * URL of supplementary document uploaded by School/Partnership for AI context.
     * Only applicable when source = AI_GENERATED.
     * The AI uses content from this document alongside waste item data to
     * generate more contextually relevant questions.
     */
    @Column(name = "source_document_url", length = 500)
    private String sourceDocumentUrl;

    /**
     * The RoundGameConfig this AI quiz was generated for.
     * Provides the set of waste items (via allowedSubCategories) that were
     * used as AI context. NULL for manually created quizzes.
     *
     * Note: after generation and confirmation, the quiz is saved independently
     * and can be reused across other rounds/campaigns.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "generated_for_round_game_config_id")
    private RoundGameConfig generatedForRoundGameConfig;

    // ── Scoring / completion ──────────────────────────────────────────────────

    @Column(name = "time_per_question")
    private Integer timePerQuestion;

    @Column(name = "pass_score_percentage", nullable = false)
    private int passScorePercentage = 70;

    /**
     * Coin awarded to student on quiz completion (School campaigns only).
     * NULL or 0 for Partnership campaigns.
     */
    @Column(name = "coins_on_pass")
    private Integer coinsOnPass;

    // ── Lifecycle ─────────────────────────────────────────────────────────────

    /**
     * false = draft/preview state (AI-generated quiz not yet confirmed by creator).
     * true  = confirmed and available for use in campaigns.
     *
     * AI-generated flow:
     *   1. AI generates questions → quiz saved with isPublished = false (preview)
     *   2. School/Partnership reviews & optionally edits questions
     *   3. School/Partnership confirms → isPublished = true
     *   Only after step 3 is the AiGenerationLog.usageCharged set to true.
     */
    @Column(nullable = false)
    private boolean isPublished = false;

    @Column(nullable = false)
    private boolean isActive = true;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private QuizCreated createdBy;

    // ── Inverse ───────────────────────────────────────────────────────────────

    @OneToMany(mappedBy = "quiz", fetch = FetchType.LAZY)
    private List<QuizQuestion> questions;
}
